# JMSI18nRoutingBundle Configuration
jms_i18n_routing:
    default_locale: '%kernel.default_locale%'
    locales: '%supported_locales%'
    strategy: custom
    hosts:
        en: "%website_url%"
        es: "es.%website_url%"
#        de: "de.%website_url%"
    redirect_to_host: true