# NelmioApiDocBundle Configuration
nelmio_api_doc:
    documentation:
        info:
            title: ThronesDB API
            version: 1.0.0
            description: ThronesDB's public and protected APIs endpoints.
    areas:
        path_patterns: # an array of regexps
            - ^/api/oauth2/deck/
            - ^/api/oauth2/decks/
            - ^/api/public/card/
            - ^/api/public/cards/
            - ^/api/public/decklist/
            - ^/api/public/decklists/
            - ^/api/public/packs/