twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        "%kernel.project_dir%/src/Resources/FOSOAuthServerBundle/views" : FOSOAuthServerBundle
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        default_locale: '%kernel.default_locale%'
        supported_locales: '%supported_locales%'
        cards_data: '@App\Services\CardsData'
        deck_validation_helper: '@App\Services\DeckValidationHelper'
        google_analytics_tracking_code: '%google_analytics_tracking_code%'
        allow_search_engine_tracking: '%allow_search_engine_tracking%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
