app_api:
  resource: "app_api.yaml"
  prefix: /api
  options:
    i18n: false

app_cards:
  resource: "app_cards.yaml"
  prefix: /

app_deck:
  resource: "app_deck.yaml"
  prefix: /deck

app_decklist:
  resource: "app_decklist.yaml"
  prefix: /decklist

app_review:
  resource: "app_review.yaml"
  prefix: /review

app_tag:
  resource: "app_tag.yaml"
  prefix: /tag

app_user:
  resource: "app_user.yaml"
  prefix: /user

donators:
  path: /donators
  methods: [GET]
  defaults:
    _controller: App\Controller\SocialController:donatorsAction

decks_list:
  path: /decks
  methods: [GET]
  defaults:
    _controller: App\Controller\BuilderController:listAction

decklists_searchform:
  path: /decklists/search
  methods: [GET]
  defaults:
    _controller: App\Controller\SocialController:searchAction

decklists_list:
  path: /decklists/{type}/{page}
  methods: [GET]
  defaults:
    _controller: App\Controller\SocialController:listAction
    type: popular
    page: 1
  requirements:
    page: \d+

card_reviews_list:
  path: /reviews/{page}
  defaults:
    _controller: App\Controller\ReviewController:listAction
    page: 1
  requirements:
    page: \d+

