api_oauth2_user:
    path: /user
    methods: [GET]
    defaults:
        _controller: App\Controller\Oauth2Controller:userAction

api_oauth2_decks:
    path: /decks
    methods: [GET]
    defaults:
        _controller: App\Controller\Oauth2Controller:listDecksAction

api_oauth2_load_deck:
    path: /deck/load/{id}
    methods: [GET]
    defaults:
        _controller: App\Controller\Oauth2Controller:loadDeckAction
    requirements:
        id: \d+

api_oauth2_save_deck:
    path: /deck/save/{id}
    methods: [PUT]
    defaults:
        _controller: App\Controller\Oauth2Controller:saveDeckAction
    requirements:
        id: \d+

api_oauth2_publish_deck:
    path: /deck/publish/{id}
    methods: [PUT]
    defaults:
        _controller: App\Controller\Oauth2Controller:publishDeckAction
    requirements:
        id: \d+
