remind_email:
    path:     /remind/{username}
    defaults:
        _controller: App\Controller\UserController:remindAction

user_profile_public:
    path: /profile/{user_id}/{user_name}/{page}
    methods: [GET]
    defaults:
        _controller: App\Controller\UserController:publicProfileAction
        page: 1
    requirements:
        user_id: \d+

user_profile_edit:
    path: /profile_edit
    methods: [GET]
    defaults:
        _controller: App\Controller\UserController:editProfileAction

user_profile_save:
    path: /profile_save
    methods: [POST]
    defaults:
        _controller: App\Controller\UserController:saveProfileAction

decklist_favorite:
    path: /favorite
    methods: [POST]
    defaults:
        _controller: App\Controller\SocialController:favoriteAction

decklist_like:
    path: /like
    methods: [POST]
    defaults:
        _controller: App\Controller\SocialController:voteAction

decklist_comment:
    path: /comment
    methods: [POST]
    defaults:
        _controller: App\Controller\SocialController:commentAction

decklist_comment_hide:
    path: /hidecomment/{comment_id}/{hidden}
    methods: [POST]
    defaults:
        _controller: App\Controller\SocialController:hidecommentAction

card_reviews_list_byauthor:
    path: /reviews/{user_id}/{page}
    defaults:
        _controller: App\Controller\ReviewController:byauthorAction
        page: 1
    requirements:
        page: \d+
        user_id: \d+
