remind_email:
    path: /user/remind/{username}
    defaults:
        _controller: App\Controller\UserController:remindAction

user_profile_public:
    path: /user/profile/{user_id}/{user_name}/{page}
    methods: [GET]
    defaults:
        _controller: App\Controller\UserController:publicProfileAction
        page: 1
    requirements:
        user_id: \d+

user_profile_edit:
    path: /user/profile_edit
    methods: [GET]
    defaults:
        _controller: App\Controller\UserController:editProfileAction

user_profile_save:
    path: /user/profile_save
    methods: [POST]
    defaults:
        _controller: App\Controller\UserController:saveProfileAction
