cards_list:
    path: /set/{pack_code}/{view}/{sort}/{page}
    defaults:
        _controller: App\Controller\SearchController:listAction
        view: list
        sort: set
        page: 1

cards_zoom:
    path: /card/{card_code}
    defaults:
        _controller: App\Controller\SearchController:zoomAction

cards_cycle:
    path: /cycle/{cycle_code}/{view}/{sort}/{page}
    defaults:
        _controller: App\Controller\SearchController:cycleAction
        view: list
        sort: faction
        page: 1

cards_search:
    path: /search
    defaults:
        _controller: App\Controller\SearchController:formAction

cards_find:
    path: /find
    defaults:
        _controller: App\Controller\SearchController:findAction

cards_processSearchForm:
    path: /process
    defaults:
        _controller: App\Controller\SearchController:processAction
