deck_buildform:
    path:  /new
    methods: [GET]
    defaults:
        _controller: AppBundle:Builder:buildform

deck_initbuild:
    path: /build
    methods: [POST]
    defaults:
        _controller: AppBundle:Builder:initbuild

deck_save:
    path: /save
    methods: [POST]
    defaults:
        _controller: AppBundle:Builder:save

deck_edit:
    path: /edit/{deck_uuid}
    methods: [GET]
    defaults:
        _controller: AppBundle:Builder:edit
    requirements:
        deck_uuid: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'

deck_view:
    path: /view/{deck_uuid}
    methods: [GET]
    defaults:
        _controller: AppBundle:Builder:view
    requirements:
        deck_uuid: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'

deck_clone:
    path: /clone/{deck_uuid}
    methods: [GET]
    defaults:
        _controller: AppBundle:Builder:clone
    requirements:
        deck_uuid: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'

deck_delete:
    path: /delete
    methods: [POST]
    defaults:
        _controller: AppBundle:Builder:delete

deck_delete_list:
    path: /delete_list
    methods: [POST]
    defaults:
        _controller: AppBundle:Builder:deleteList

deck_import:
    path: /import
    methods: [GET]
    defaults:
        _controller: AppBundle:Builder:import

deck_fileimport:
    path: /fileimport
    methods: [POST]
    defaults:
        _controller: AppBundle:Builder:fileimport

deck_copy:
    path: /copy/{decklist_id}
    defaults:
        _controller: AppBundle:Builder:copy
    requirements:
        decklist_id: \d+

deck_publish_form:
    path: /publish/{deck_uuid}
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:publishForm
    requirements:
        deck_uuid: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'

deck_download:
    path: /export/octgn/{deck_uuid}
    methods: [GET]
    defaults:
        _controller: AppBundle:Builder:download
    requirements:
        deck_uuid: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'

deck_autosave:
    path: /autosave
    methods: [POST]
    defaults:
        _controller: AppBundle:Builder:autosave

decks_diff:
    path: /compare/{deck1_uuid}/{deck2_uuid}
    methods: [GET]
    defaults:
        _controller: AppBundle:Builder:compare
    requirements:
        deck1_uuid: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'
        deck2_uuid: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'
